### ISSUE TITLE
SecureHeaders middleware erases all cookies in Rack 3 due to \n joining

### ISSUE THREAD

**Issue by collinsauve** [github/secure_headers#514]
# Bugs

SecureHeaders is not compatible with this change from [Rack 3](https://github.com/rack/rack/blob/main/UPGRADE-GUIDE.md#multiple-response-header-values-are-encoded-using-an-array) as SH uses `\n` encoded cookies in [flag_cookies!](https://github.com/github/secure_headers/blob/main/lib/secure_headers/middleware.rb#L29):

> Response header values can be an Array to handle multiple values (and no longer supports \n encoded headers).

Rack will no longer transform this back into an array for you, and that joined string with `\n` gets all the way to [Puma::Request#str_headers](https://github.com/puma/puma/blob/master/lib/puma/request.rb#L649C14-L649C26) at which point it ignores it due to it being an illegal value.

### Expected outcome

Describe what you expected to happen 

1. I set multiple cookies
1. Those cookies are included in the response

### Actual outcome

1. The response written to the socket does not include any cookies set before SH middleware gets them.

**Comment by collinsauve** [comment]
I've put together a minimum-viable reproduction of the issue:
https://github.com/collinsauve/secure-headers-issue-514

**Comment by adfoster-r7** [comment]
I'm also hitting an error for this code path, but now from the thin 2.x upgrade a validaiton error is raised due to the `\n` char being present:

```
 2025-07-31 00:53:14 +0100 Unexpected error while processing request: Header contains CR or LF
 	/Users/user/.rvm/gems/ruby-3.3.8@app/gems/thin-2.0.1/lib/thin/headers.rb:32:in `[]='
 	/Users/user/.rvm/gems/ruby-3.3.8@app/gems/thin-2.0.1/lib/thin/response.rb:101:in `block (2 levels) in headers='
 	/Users/user/.rvm/gems/ruby-3.3.8@app/gems/thin-2.0.1/lib/thin/response.rb:101:in `each'
 	/Users/user/.rvm/gems/ruby-3.3.8@app/gems/thin-2.0.1/lib/thin/response.rb:101:in `block in headers='
 	/Users/user/.rvm/gems/ruby-3.3.8@app/gems/thin-2.0.1/lib/thin/response.rb:96:in `each'
 	/Users/user/.rvm/gems/ruby-3.3.8@app/gems/thin-2.0.1/lib/thin/response.rb:96:in `headers='
 	/Users/user/.rvm/gems/ruby-3.3.8@app/gems/thin-2.0.1/lib/thin/connection.rb:106:in `post_process'
 	/Users/user/.rvm/gems/ruby-3.3.8@app/gems/thin-2.0.1/lib/thin/connection.rb:53:in `process'
 	/Users/user/.rvm/gems/ruby-3.3.8@app/gems/thin-2.0.1/lib/thin/connection.rb:39:in `receive_data'
 	/Users/user/.rvm/gems/ruby-3.3.8@app/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
 	/Users/user/.rvm/gems/ruby-3.3.8@app/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
 	/Users/user/.rvm/gems/ruby-3.3.8@app/gems/thin-2.0.1/lib/thin/backends/base.rb:75:in `start'
 	/Users/user/.rvm/gems/ruby-3.3.8@app/gems/thin-2.0.1/lib/thin/server.rb:162:in `start'
 	/Users/user/.rvm/gems/ruby-3.3.8@app/gems/thin-2.0.1/lib/thin/controllers/controller.rb:87:in `start'
 	/Users/user/.rvm/gems/ruby-3.3.8@app/gems/thin-2.0.1/lib/thin/runner.rb:203:in `run_command'
 	/Users/user/.rvm/gems/ruby-3.3.8@app/gems/thin-2.0.1/lib/thin/runner.rb:159:in `run!'
 	/Users/user/.rvm/gems/ruby-3.3.8@app/gems/thin-2.0.1/bin/thin:6:in `<top (required)>'
 	/Users/user/.rvm/gems/ruby-3.3.8@app/bin/thin:25:in `load'
 	/Users/user/.rvm/gems/ruby-3.3.8@app/bin/thin:25:in `<main>'
 	/Users/user/.rvm/gems/ruby-3.3.8@app/bin/ruby_executable_hooks:22:in `eval'
 	/Users/user/.rvm/gems/ruby-3.3.8@app/bin/ruby_executable_hooks:22:in `<main>'

```
